services:
  app:
    image: textdb:latest
    container_name: textdb_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://postgres:postgres@db:5432/textdb"
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/textdb"
    volumes:
      - ./priv/static/data:/app/priv/static/data
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: textdb_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: textdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
